### ISSUE TITLE
this supporter pack came up as unaccounted for

### ISSUE THREAD

**Issue by BourbonCrow** [peeteer1245/poeTransactionCounter#6]
Supporter Pack
Apr 13, 2012, 2:07:46 AM 

i have no idea what one it is but its ancient haha the text above is from my poe profile page

**Comment by BourbonCrow** [comment]
i assume its this one for 15$..
https://pathofexile.fandom.com/wiki/Supporter_pack#Closed_Beta_Supporter_Packs  the 2nd on under closed beta that gives the forum title (since i have the title) but i got no pet so it cant be the once above and it cant be the one below since that one gives no title


edit: now im not sure anymore... i had these 2 and these are the dates so i guess i first bought a cheaper pack then upgraded to 1 step higher?
Early Access Pack
Apr 14, 2012, 2:16:58 AM
Supporter Pack
Apr 13, 2012, 2:07:46 AM

**Comment by peeteer1245** [comment]
Thank you for bringing this up, and including the detailed Supporter Pack names.
Your upgrade hypothesis is interesting, since nowadays they remove the old transaction and only keep the new one.

Your USD 15 Pack is included now.
